apiVersion: v1
kind: ConfigMap
metadata:
  name: db-init-script
  namespace: three-tier-app
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS products (
      id SERIAL PRIMARY KEY,
      name VARCHAR(100) NOT NULL,
      price NUMERIC(10,2) NOT NULL
    );

    INSERT INTO products (name, price) VALUES
      ('Laptop', 1200.00),
      ('Mouse', 25.50),
      ('Keyboard', 45.00);

